### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by GregoryGHarding** [roshank231/onePaceMagnetExtractor#2]
The script runs as expected, but entering the arc title always results in no arcs found.

**Comment by srodriguezcode** [comment]
The [PR](https://github.com/roshank231/onePaceMagnetExtractor/pull/1) from SoLOeRGr solves this issue. I don't know if the owner of the repository is going to merge it tho

**Comment by roshank231** [comment]
@GregoryGHarding @srodriguezcode @SoLOeRGr 

Sorry for the delay, Merged.
